// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "kernelcad.h"

/////////////////////////////////////////////////////////////////////////////
// CKernelCAD

IMPLEMENT_DYNCREATE(CKernelCAD, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CKernelCAD properties

/////////////////////////////////////////////////////////////////////////////
// CKernelCAD operations
