// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "kernelcad.h"

/////////////////////////////////////////////////////////////////////////////
// CKernelCAD

IMPLEMENT_DYNCREATE(CKernelCAD, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CKernelCAD properties

CString CKernelCAD::GetModelPath()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CKernelCAD::SetModelPath(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

BOOL CKernelCAD::GetShowGlobalAxes()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CKernelCAD::SetShowGlobalAxes(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CKernelCAD::GetShowLocalAxes()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CKernelCAD::SetShowLocalAxes(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

long CKernelCAD::GetDIBackColor()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CKernelCAD::SetDIBackColor(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

BOOL CKernelCAD::GetRenderSolid()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void CKernelCAD::SetRenderSolid(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CKernelCAD operations

BOOL CKernelCAD::SaveAs(LPCTSTR strFilePath)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strFilePath);
	return result;
}

BOOL CKernelCAD::Save()
{
	BOOL result;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

LPUNKNOWN CKernelCAD::GetModel()
{
	LPUNKNOWN result;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_UNKNOWN, (void*)&result, NULL);
	return result;
}

BOOL CKernelCAD::UpdateSurface()
{
	BOOL result;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}
