// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "kernelcad.h"

/////////////////////////////////////////////////////////////////////////////
// KernelCAD

IMPLEMENT_DYNCREATE(KernelCAD, CWnd)

/////////////////////////////////////////////////////////////////////////////
// KernelCAD properties

CString KernelCAD::GetModelPath()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void KernelCAD::SetModelPath(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

BOOL KernelCAD::GetShowGlobalAxes()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void KernelCAD::SetShowGlobalAxes(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL KernelCAD::GetShowLocalAxes()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void KernelCAD::SetShowLocalAxes(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

long KernelCAD::GetDIBackColor()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void KernelCAD::SetDIBackColor(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

BOOL KernelCAD::GetRenderSolid()
{
	BOOL result;
	GetProperty(0x5, VT_BOOL, (void*)&result);
	return result;
}

void KernelCAD::SetRenderSolid(BOOL propVal)
{
	SetProperty(0x5, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// KernelCAD operations

BOOL KernelCAD::SaveAs(LPCTSTR strFilePath)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strFilePath);
	return result;
}

BOOL KernelCAD::Save()
{
	BOOL result;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

LPUNKNOWN KernelCAD::GetModel()
{
	LPUNKNOWN result;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_UNKNOWN, (void*)&result, NULL);
	return result;
}

BOOL KernelCAD::UpdateSurface()
{
	BOOL result;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

LPUNKNOWN KernelCAD::GetView()
{
	LPUNKNOWN result;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_UNKNOWN, (void*)&result, NULL);
	return result;
}

void KernelCAD::RequestClientDraw(BOOL request)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 request);
}

void KernelCAD::RequestEvent(long event, BOOL request)
{
	static BYTE parms[] =
		VTS_I4 VTS_BOOL;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 event, request);
}

void KernelCAD::UpdateView()
{
	InvokeHelper(0xd, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
